### PR TITLE
Multi gpu cpu support

### PR DESCRIPTION
**Pull request by 009deep**
Adding support for 
- [x] Training on Multi-gpu
- [x] Inference on CPU

### CODE REVIEW

**Comment by joonson** [comment]
We have checked the code, but found that the use of DataParallel leads to a drop in model performance. I am not sure why this happens, but this appears to be a common problem in PyTorch. We will merge the request once this problem is resolved.

**Comment by 009deep** [comment]
I understand concern. But, with few other changes, I've been able to train model to get EER as low as 1.5 % by using above code among few other changes. Also, use of single core limits model size. For example, current Resnet model uses 1/4 of filter size as compared to actual Resnet34, but if someone wants to experiment with actual size it won't be feasible on even 32 GB memory GPU. 
Adding parallelism would help with wide range of experimentation.
How much does performance differ btw? As angleproto doesn't render best result for my use case, I've not pursued it to get similar result.

**Comment by zh794390558** [comment]
Who to reproduce 1.5 EER, I will test this.

**Comment by 009deep** [comment]
Sorry,  I may release those details later in the year. But  training is done  using code in this PR. So if you want to use multi-gpu, feel free to use these changes.

**Comment by ShaneRun** [comment]
> Sorry, I may release those details later in the year. But training is done using code in this PR. So if you want to use multi-gpu, feel free to use these changes.



> I understand concern. But, with few other changes, I've been able to train model to get EER as low as 1.5 % by using above code among few other changes. Also, use of single core limits model size. For example, current Resnet model uses 1/4 of filter size as compared to actual Resnet34, but if someone wants to experiment with actual size it won't be feasible on even 32 GB memory GPU.
> Adding parallelism would help with wide range of experimentation.
> How much does performance differ btw? As angleproto doesn't render best result for my use case, I've not pursued it to get similar result.

Thank you for your effort!
May I ask a question: have you used data augmentation in order to get EER as low as 1.5 %?
Or you just use the dev set of voxceleb2?
Thank you in advance!

**Comment by 009deep** [comment]
With dev set of voxceleb2 + augmentation you can get below 1.5. 
But, it's not just data, there are other changes including network architecture, loss and hyper parameter tuning. As I said I may release those details later this year.

**Comment by Shane-pe** [comment]
> With dev set of voxceleb2 + augmentation you can get below 1.5.
> But, it's not just data, there are other changes including network architecture, loss and hyper parameter tuning. As I said I may release those details later this year.

@009deep 
Cool, looking forward to your disclosure on those improvement.
BTW, I am curious on your data augmentation method, are you used the typical 5-fold data augmentation recipe from Kaldi?
Or you had tried different method?

**Comment by 009deep** [comment]
I obtained results using standard kaldi recipes.

**Comment by joonson** [comment]
`DataParallel` is no longer recommended in PyTorch. We updated the trainer with `DistributedDataParallel`.

**Pull request closed without merging**
